require('settings')

require('color.catppuccin')
require('plugins')
require('nvimtree')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.complete')
--require('lsp-config.nvim-cmp')
require('lua-line')
require('treesitter-config')
require('refactor.ref')
--require('test')
